{{- if .Values.version }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.replication.defaultReplicationFactor }}
  roles:
    - controller
  template:
    kafkaContainer:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
{{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.labels }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
{{- range $key, $val := .Values.labels }}
                  - key: {{ $key }}
                    operator: In
                    values:
                      - {{ quote $val }}
{{- end }}
{{- end }}
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
{{- end }}
