{{- if .Values.topics }}
{{- $cluster := .Values.kafka.clusterName | default "my-cluster" }}
{{- range $name, $topic := .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $name }}
  labels:
    strimzi.io/cluster: {{ $cluster }}
spec:
  partitions: {{ $topic.partitions | default 10 }}
  replicas: {{ $topic.replicas | default 3 }}
---
{{- end }}
{{- end }}
