{{- if .Values.users }}
{{- $cluster := .Values.kafka.clusterName | default "my-cluster" }}
{{- range $username, $user := .Values.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ $username }}
  labels:
    strimzi.io/cluster: {{ $cluster }}
spec:
  authentication:
    type: {{ $user.authenticationType | default "tls" }}
  authorization:
    type: {{ $user.authorizationType | default "simple" }}
    acls:
{{- range $acl := $user.acls }}
      - resource:
          type: {{ $acl.type | default "topic" }}
          name: {{ $acl.name }}
          patternType: {{ $acl.patternType | default "literal" }}
        operations:
{{- range $op := $acl.operations }}
          - {{ $op }}
{{- end }}
        host: {{ $acl.host | default "*" }}
{{- end }}
---
{{- end }}
{{- end }}
