{{- if .Values.kafka.version }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    metadataVersion: {{ .Values.kafka.metadataVersion }}
    template:
      pod:
        securityContext:
          runAsUser: 1000001
          fsGroup: 0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    authorization:
      type: simple
    config:
      auto.create.topics.enable: {{ .Values.kafka.autoCreateTopics }}
      offsets.topic.replication.factor: {{ .Values.kafka.replication.offsetsReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replication.transactionStateReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.replication.transactionStateMinInSyncReplica }}
      default.replication.factor: {{ .Values.kafka.replication.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.kafka.replication.minInSyncReplicas }}
    resources:
      requests:
        memory: {{ .Values.kafka.resources.memory }}
        cpu: {{ .Values.kafka.resources.cpuRequest }}
      limits:
        memory: {{ .Values.kafka.resources.memory }}
        cpu: {{ .Values.kafka.resources.cpuLimit }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
{{- end }}
