{{- if .Values.topics }}
{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
{{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ quote $val }}
{{- end }}
spec:
  partitions: {{ default 10 .partitions }}
  replicas: {{ default 3 .replicas }}
{{- end }}
{{- end }}
