{{- if .Values.version }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.version }}
    metadataVersion: {{ .Values.metadataVersion }}
    template:
      kafkaContainer:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      pod:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
{{- if .Values.tolerations }}
        tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.labels }}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
{{- range $key, $val := .Values.labels }}
                    - key: {{ $key }}
                      operator: In
                      values:
                        - {{ quote $val }}
{{- end }}
{{- end }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    authorization:
      type: simple
    config:
      auto.create.topics.enable: {{ .Values.autoCreateTopics }}
      offsets.topic.replication.factor: {{ .Values.replication.offsetsReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.replication.transactionStateReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.replication.transactionStateMinInSyncReplica }}
      default.replication.factor: {{ .Values.replication.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.replication.minInSyncReplicas }}
    resources:
      requests:
        memory: {{ .Values.resources.memory }}
        cpu: {{ .Values.resources.cpuRequest }}
      limits:
        memory: {{ .Values.resources.memory }}
        cpu: {{ .Values.resources.cpuLimit }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          seccompProfile:
            type: RuntimeDefault
      topicOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
              - ALL
      userOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
              - ALL
{{- end }}
