{{- if .Values.users }}
{{- range .Values.users }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.clusterName }}
spec:
  authentication:
    type: {{ .authenticationType | default "tls" }}
  authorization:
    type: {{ .authorizationType | default "simple" }}
    acls:
      {{- range .acls }}
      - resource:
          type: {{ .type }}
          name: {{ .name }}
          patternType: {{ .patternType | default "literal" }}
        operations:
{{ toYaml .operations | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
